### ISSUE TITLE
Unfork cosmos sdk to hub's cosmos sdk v0.45.3

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [CudoVentures/cudos-node#104]
This is a high priority item for this release. Our goal is to replace cosmos sdk custom dependency to canonical version of 0.45.16

- [x] #105 
- [x] write unit tests for modified logic
- [x] remove forked version

Here are relevent resources:
1. According to limechain, here is the current branch for modified sdk: https://github.com/CudoVentures/cosmos-sdk/tree/cudos-master. 

## project manager tasks

- [x] create an issue and task break down for each items above

@dao-notional @tropicaldog @tnv1

**Comment by nghuyenthevinh2000** [comment]
https://notionalgroup.slack.com/archives/C064VQK5C3W/p1703064966411509

**Comment by tnv1** [comment]
As [my note](https://github.com/CudoVentures/cudos-node/issues/105#issuecomment-1868698038). Here is plan for unfork `cosmos-sdk` and using `cosmos-sdk` original v0.45.16

1. Remove replace [cosmos-sdk](https://github.com/CudoVentures/cudos-node/blob/994a9ec16ef365af5ee239d58686da533dceaab7/go.mod#L47C1-L48C1) forked version and change it to `github.com/cosmos/cosmos-sdk v0.45.16`. And it needs to replace `github.com/tendermint/tendermint => github.com/cometbft/cometbft v0.34.27 `
2. Safe to remove some dependencies of `x/group` in app because `x/group` is not existed in `comos-sdk v0.45.16`.
3. Should remove `simapp` in this version?
4. Add `ante` to `app` for adding some decorators check for validate msg `VerifyInvariant` in `x/crisis` and `MsgCreateValidator` in `x/staking`
4. Add custom bank module instead of modifying `BurnCoins` in `msg_server`.
5. Write new unit tests with `apptesting` like osmosis
6. Should organize new upgrades folder like Osmosis-style?
7. Write upgrade plan handler.
8. Add some scripts upgrade-test.
9. Should upgrade to `go1.19`?

@nghuyenthevinh2000  please review it!

**Comment by nghuyenthevinh2000** [comment]
code is done
