### ISSUE TITLE
simapp refactoring

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [CudoVentures/cudos-node#106]
clean simapp, use apptesting
@dao-notional

**Comment by dao-notional** [comment]
Okay, to remove simapp. I need to see all the testcases, the checking that `simapp` are doing. Then I will migrate these checking to `app` itself

**Comment by dao-notional** [comment]
Hi @nghuyenthevinh2000 , because there are no testcase using `simapp`, so I'm raise a PR to clean `simapp` only. For `apptesting`, it depends on some external library. I will raise a separate PR to install it. 
This is PR for cleaning `simapp` only:
https://github.com/CudoVentures/cudos-node/pull/107

**Comment by dao-notional** [comment]
@nghuyenthevinh2000 , this is PR for adding app testing
https://github.com/CudoVentures/cudos-node/pull/109
