### ISSUE TITLE
unknown field 'IncrementModifier'

### ISSUE THREAD

**Issue by leezhiengammobox** [CudoVentures/cudos-node#39]
I'm getting the following error when serving the node with starport/ignite:
```
../../x/cudoMint/types/params.go:25:3: unknown field 'IncrementModifier' in struct literal of type Params
../../x/cudoMint/types/params.go:32:3: unknown field 'IncrementModifier' in struct literal of type Params
../../x/cudoMint/types/params.go:38:40: p.IncrementModifier undefined (type Params has no field or method IncrementModifier)
../../x/cudoMint/types/params.go:49:52: p.IncrementModifier undefined (type *Params has no field or method IncrementModifier)
```

**Comment by V-Staykov** [comment]
In this node we use a forked and quite changed version of cosmos-sdk. Also the error you get is because of our custom mint module, which ignite probably can't initiate properly. Because of this it is expected that Ignite doesn't work well. We have extensive guides and also developed cudos-blast for testing purposes, which you can check here: https://github.com/CudoVentures/cudos-blast
